# Generated by Django 3.1.7 on 2021-03-03 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_services', '0002_auto_20210303_1937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsstories',
            old_name='aurthor',
            new_name='author',
        ),
    ]
